type GradeId = 7 | 8 | 9 | 10 | 11 | 12;
type FieldId = 1 | 2 | 3 | 4 | 5 | null;

export type Grade = {
  id: GradeId;
  value: GradeId;
  label: string;
  dore: string;
};

export const GRADES: Grade[] = [
  { id: 7, value: 7, dore: "متوسطه اول", label: "هفتم" },
  { id: 8, value: 8, dore: "متوسطه اول", label: "هشتم" },
  { id: 9, value: 9, dore: "متوسطه اول", label: "نهم" },
  { id: 10, value: 10, dore: "متوسطه دوم", label: "دهم" },
  { id: 11, value: 11, dore: "متوسطه دوم", label: "یازدهم" },
  { id: 12, value: 12, dore: "متوسطه دوم", label: "دوازدهم" },
];

export type Field = {
  id: FieldId;
  value: FieldId;
  label: string;
};

export const FIELDS: Field[] = [
  { id: 1, value: 1, label: "تجربی" },
  { id: 2, value: 2, label: "انسانی" },
  { id: 3, value: 3, label: "ریاضی" },
  // { id: 4, value: 4, label: "معارف" },
  // { id: 5, value: 5, label: "هنر" },
];

export type Book = {
  id: string; // is not uid
  value: string;
  label: string;
  gradeId: GradeId;
  fieldId: FieldId;
  coverImage: string;
  isAvailable: boolean;
  lastPage: number;
  publishedYear: number;
  hasFinalExam: boolean;
  isInKonkour: boolean;
};

export const BOOKS: Book[] = [
  // ================= پایه هفتم =================
  {
    id: "701",
    value: "701",
    label: "آموزش قرآن",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C701.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "702",
    value: "702",
    label: "پیام های آسمان",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C702.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "703",
    value: "703",
    label: "فارسی",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C703.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "704",
    value: "704",
    label: "نگارش",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C704.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "705",
    value: "705",
    label: "ریاضی",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C705.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "706",
    value: "706",
    label: "علوم تجربی ۷",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C706.jpg",
    isAvailable: true,
    lastPage: 138,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "707",
    value: "707",
    label: "مطالعات اجتماعی",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C707.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "708",
    value: "708",
    label: "فرهنگ و هنر",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C708.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "709",
    value: "709",
    label: "عربی",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C709.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "710",
    value: "710",
    label: "انگلیسی ۱",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C710.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "711",
    value: "711",
    label: "کتاب کار انگلیسی ۱",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C711.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "712",
    value: "712",
    label: "تفکر و سبک زندگی (پسران)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C712.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "713",
    value: "713",
    label: "تفکر و سبک زندگی (دختران)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C713.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "717",
    value: "717",
    label: "کار و فناوری",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C717.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "7171",
    value: "7171",
    label: "کار و فناوری (اجرای آزمایشی)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C7171.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "719",
    value: "719",
    label: "ضمیمه پیام های آسمان (اهل سنت)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C719.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "720",
    value: "720",
    label: "تعلیمات ادیان الهی و اخلاق (اقلیت ها)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C720.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "722",
    value: "722",
    label: "فارسی و نگارش (استعدادهای درخشان)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C722.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "723",
    value: "723",
    label: "ریاضیات (استعدادهای درخشان)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C723.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "724",
    value: "724",
    label: "علوم تجربی (استعدادهای درخشان)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C724.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "741",
    value: "741",
    label: "تربیت دینی (از من تا خدا)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C741.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "742",
    value: "742",
    label: "تربیت دینی (اهل سنت)",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C742.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "765",
    value: "765",
    label: "از ایرانمان دفاع می کنیم",
    gradeId: 7,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C765.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },

  // ================= پایه هشتم =================
  {
    id: "801",
    value: "801",
    label: "آموزش قرآن",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C801.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "802",
    value: "802",
    label: "پیام های آسمان",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C802.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "803",
    value: "803",
    label: "فارسی",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C803.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "804",
    value: "804",
    label: "نگارش",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C804.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "805",
    value: "805",
    label: "ریاضی",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C805.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "806",
    value: "806",
    label: "علوم تجربی ۸",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C806.jpg",
    isAvailable: true,
    lastPage: 146,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "807",
    value: "807",
    label: "مطالعات اجتماعی",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C807.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "808",
    value: "808",
    label: "فرهنگ و هنر",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C808.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "809",
    value: "809",
    label: "عربی",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C809.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "810",
    value: "810",
    label: "انگلیسی ۲",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C810.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "811",
    value: "811",
    label: "کتاب کار انگلیسی ۲",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C811.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "812",
    value: "812",
    label: "تفکر و سبک زندگی",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C812.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "814",
    value: "814",
    label: "تفکر و سبک زندگی (پسران)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C814.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "817",
    value: "817",
    label: "کار و فناوری",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C817.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "8171",
    value: "8171",
    label: "کار و فناوری (اجرای آزمایشی)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C8171.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "819",
    value: "819",
    label: "ضمیمه پیام های آسمان (اهل سنت)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C819.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "820",
    value: "820",
    label: "تعلیمات ادیان الهی و اخلاق (اقلیت ها)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C820.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "822",
    value: "822",
    label: "فارسی و نگارش (استعدادهای درخشان)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C822.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "823",
    value: "823",
    label: "ریاضیات (استعدادهای درخشان)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C823.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "824",
    value: "824",
    label: "علوم تجربی (استعدادهای درخشان)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C824.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "841",
    value: "841",
    label: "تربیت دینی (از من تا خدا)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C841.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "842",
    value: "842",
    label: "تربیت دینی (اهل سنت)",
    gradeId: 8,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C842.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },

  // ================= پایه نهم =================
  {
    id: "901",
    value: "901",
    label: "آموزش قرآن",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C901.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "902",
    value: "902",
    label: "پیام های آسمان",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C902.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "903",
    value: "903",
    label: "فارسی",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C903.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "904",
    value: "904",
    label: "نگارش",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C904.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "905",
    value: "905",
    label: "ریاضی",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C905.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "906",
    value: "906",
    label: "علوم تجربی ۹",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C906.jpg",
    isAvailable: true,
    lastPage: 176,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "907",
    value: "907",
    label: "مطالعات اجتماعی",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C907.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "908",
    value: "908",
    label: "فرهنگ و هنر",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C908.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "909",
    value: "909",
    label: "عربی",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C909.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "910",
    value: "910",
    label: "انگلیسی ۳",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C910.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "911",
    value: "911",
    label: "کتاب کار انگلیسی ۳",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C911.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "915",
    value: "915",
    label: "آمادگی دفاعی",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C915.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "917",
    value: "917",
    label: "کار و فناوری",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C917.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "9171",
    value: "9171",
    label: "کار و فناوری (اجرای آزمایشی)",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C9171.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "919",
    value: "919",
    label: "ضمیمه پیام های آسمان (اهل سنت)",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C919.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "920",
    value: "920",
    label: "تعلیمات ادیان الهی و اخلاق (اقلیت ها)",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C920.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "922",
    value: "922",
    label: "فارسی و نگارش (استعدادهای درخشان)",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C922.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "923",
    value: "923",
    label: "ریاضیات (استعدادهای درخشان)",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C923.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "924",
    value: "924",
    label: "علوم تجربی (استعدادهای درخشان)",
    gradeId: 9,
    fieldId: null,
    coverImage: "@/public/imgs/book-covers/C924.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },

  // ================= پایه دهم =================
  // مشترک (fieldId: null)
  {
    id: "110201",
    value: "110201",
    label: "فارسی ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110201",
    value: "110201",
    label: "فارسی ۱",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110201",
    value: "110201",
    label: "فارسی ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110201",
    value: "110201",
    label: "فارسی ۱",
    gradeId: 10,
    fieldId: 4,
    coverImage: "@/public/imgs/book-covers/C110201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110202",
    value: "110202",
    label: "نگارش ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110202",
    value: "110202",
    label: "نگارش ۱",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110202",
    value: "110202",
    label: "نگارش ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110202",
    value: "110202",
    label: "نگارش ۱",
    gradeId: 10,
    fieldId: 4,
    coverImage: "@/public/imgs/book-covers/C110202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110204",
    value: "110204",
    label: "دین و زندگی ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110204.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110204",
    value: "110204",
    label: "دین و زندگی ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110204.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110206",
    value: "110206",
    label: "عربی، زبان قرآن ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110206.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110206",
    value: "110206",
    label: "عربی، زبان قرآن ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110206.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110210",
    value: "110210",
    label: "شیمی ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110210.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110210",
    value: "110210",
    label: "شیمی ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110210.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110211",
    value: "110211",
    label: "ریاضی ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110211.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110211",
    value: "110211",
    label: "ریاضی ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110211.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110215",
    value: "110215",
    label: "آمادگی دفاعی",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110215.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110215",
    value: "110215",
    label: "آمادگی دفاعی",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110215.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110215",
    value: "110215",
    label: "آمادگی دفاعی",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110215.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110217",
    value: "110217",
    label: "آزمایشگاه علوم تجربی ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110217.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110217",
    value: "110217",
    label: "آزمایشگاه علوم تجربی ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110217.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110218",
    value: "110218",
    label: "جغرافیای ایران",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110218.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110218",
    value: "110218",
    label: "جغرافیای ایران",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110218.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110218",
    value: "110218",
    label: "جغرافیای ایران",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110218.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110222",
    value: "110222",
    label: "هنر",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110222.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110222",
    value: "110222",
    label: "هنر",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110222.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110222",
    value: "110222",
    label: "هنر",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110222.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110224",
    value: "110224",
    label: "کارگاه کارآفرینی و تولید",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110224.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110224",
    value: "110224",
    label: "کارگاه کارآفرینی و تولید",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110224.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110224",
    value: "110224",
    label: "کارگاه کارآفرینی و تولید",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110224.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110225",
    value: "110225",
    label: "تفکر و سواد رسانه ای",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110225.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110225",
    value: "110225",
    label: "تفکر و سواد رسانه ای",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110225.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110225",
    value: "110225",
    label: "تفکر و سواد رسانه ای",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110225.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110228",
    value: "110228",
    label: "تعلیمات ادیان الهی و اخلاق ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110228",
    value: "110228",
    label: "تعلیمات ادیان الهی و اخلاق ۱",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110228",
    value: "110228",
    label: "تعلیمات ادیان الهی و اخلاق ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110230",
    value: "110230",
    label: "انگلیسی ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110231",
    value: "110231",
    label: "کتاب کار انگلیسی ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110230",
    value: "110230",
    label: "انگلیسی ۱",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110231",
    value: "110231",
    label: "کتاب کار انگلیسی ۱",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110230",
    value: "110230",
    label: "انگلیسی ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110231",
    value: "110231",
    label: "کتاب کار انگلیسی ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110345",
    value: "110345",
    label: "از ایرانمان دفاع می کنیم",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110345.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110345",
    value: "110345",
    label: "از ایرانمان دفاع می کنیم",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110345.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110345",
    value: "110345",
    label: "از ایرانمان دفاع می کنیم",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110345.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی تجربی
  {
    id: "110214",
    value: "110214",
    label: "فیزیک ۱ (تجربی)",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110214.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110216",
    value: "110216",
    label: "زیست شناسی ۱",
    gradeId: 10,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C110216.jpg",
    isAvailable: true,
    lastPage: 112,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی انسانی
  {
    id: "110203",
    value: "110203",
    label: "علوم و فنون ادبی ۱",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110203.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110205",
    value: "110205",
    label: "دین و زندگی ۱ (انسانی)",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110205.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110207",
    value: "110207",
    label: "عربی، زبان قرآن ۱ (انسانی)",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110207.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110212",
    value: "110212",
    label: "ریاضی و آمار ۱",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110212.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110219",
    value: "110219",
    label: "تاریخ ۱ (ایران و جهان باستان)",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110219.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110220",
    value: "110220",
    label: "جامعه شناسی ۱",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110220.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110221",
    value: "110221",
    label: "اقتصاد",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110221.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110223",
    value: "110223",
    label: "منطق",
    gradeId: 10,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C110223.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی ریاضی
  {
    id: "110209",
    value: "110209",
    label: "فیزیک ۱ (ریاضی)",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110209.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "110213",
    value: "110213",
    label: "هندسه ۱",
    gradeId: 10,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C110213.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },

  // ================= پایه یازدهم =================
  // مشترک (fieldId: null)
  {
    id: "111201",
    value: "111201",
    label: "فارسی ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111201",
    value: "111201",
    label: "فارسی ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111201",
    value: "111201",
    label: "فارسی ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111202",
    value: "111202",
    label: "نگارش ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111202",
    value: "111202",
    label: "نگارش ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111202",
    value: "111202",
    label: "نگارش ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111204",
    value: "111204",
    label: "دین و زندگی ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111204.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111204",
    value: "111204",
    label: "دین و زندگی ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111204.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111206",
    value: "111206",
    label: "عربی، زبان قرآن ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111206.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111206",
    value: "111206",
    label: "عربی، زبان قرآن ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111206.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111210",
    value: "111210",
    label: "شیمی ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111210.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111210",
    value: "111210",
    label: "شیمی ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111210.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111217",
    value: "111217",
    label: "آزمایشگاه علوم تجربی ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111217.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111217",
    value: "111217",
    label: "آزمایشگاه علوم تجربی ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111217.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111220",
    value: "111220",
    label: "تاریخ معاصر ایران",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111220.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111220",
    value: "111220",
    label: "تاریخ معاصر ایران",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111220.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111228",
    value: "111228",
    label: "تعلیمات ادیان الهی و اخلاق ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111228",
    value: "111228",
    label: "تعلیمات ادیان الهی و اخلاق ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111228",
    value: "111228",
    label: "تعلیمات ادیان الهی و اخلاق ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111230",
    value: "111230",
    label: "انگلیسی ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111231",
    value: "111231",
    label: "کتاب کار انگلیسی ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111230",
    value: "111230",
    label: "انگلیسی ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111231",
    value: "111231",
    label: "کتاب کار انگلیسی ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111230",
    value: "111230",
    label: "انگلیسی ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111231",
    value: "111231",
    label: "کتاب کار انگلیسی ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111237",
    value: "111237",
    label: "زمین شناسی",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111237.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111237",
    value: "111237",
    label: "زمین شناسی",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111237.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111238",
    value: "111238",
    label: "ضمیمه دین و زندگی ۲ (اهل سنت)",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111238.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111238",
    value: "111238",
    label: "ضمیمه دین و زندگی ۲ (اهل سنت)",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111238.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111238",
    value: "111238",
    label: "ضمیمه دین و زندگی ۲ (اهل سنت)",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111238.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111268",
    value: "111268",
    label: "انسان و محیط زیست",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111268.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111268",
    value: "111268",
    label: "انسان و محیط زیست",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111268.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111268",
    value: "111268",
    label: "انسان و محیط زیست",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111268.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی تجربی
  {
    id: "111211",
    value: "111211",
    label: "ریاضی ۲ (تجربی)",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111211.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111216",
    value: "111216",
    label: "زیست شناسی ۲",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111216.jpg",
    isAvailable: true,
    lastPage: 154,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111244",
    value: "111244",
    label: "فیزیک ۲ (تجربی)",
    gradeId: 11,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C111244.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی انسانی
  {
    id: "111203",
    value: "111203",
    label: "علوم و فنون ادبی ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111203.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111205",
    value: "111205",
    label: "دین و زندگی ۲ (انسانی)",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111205.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111207",
    value: "111207",
    label: "عربی، زبان قرآن ۲ (انسانی)",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111207.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111212",
    value: "111212",
    label: "ریاضی و آمار ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111212.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111218",
    value: "111218",
    label: "جغرافیای ۲ (ناحیه ای)",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111218.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111219",
    value: "111219",
    label: "تاریخ ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111219.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111222",
    value: "111222",
    label: "جامعه شناسی ۲",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111222.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111224",
    value: "111224",
    label: "روان شناسی",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111224.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111226",
    value: "111226",
    label: "فلسفه ۱",
    gradeId: 11,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C111226.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی ریاضی
  {
    id: "111209",
    value: "111209",
    label: "فیزیک ۲ (ریاضی)",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111209.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111213",
    value: "111213",
    label: "هندسه ۲",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111213.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111214",
    value: "111214",
    label: "حسابان ۱",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111214.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "111215",
    value: "111215",
    label: "آمار و احتمال",
    gradeId: 11,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C111215.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },

  // ================= پایه دوازدهم =================
  // مشترک (fieldId: null)
  {
    id: "112201",
    value: "112201",
    label: "فارسی ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112201",
    value: "112201",
    label: "فارسی ۳",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112201",
    value: "112201",
    label: "فارسی ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112201.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112202",
    value: "112202",
    label: "نگارش ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112202",
    value: "112202",
    label: "نگارش ۳",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112202",
    value: "112202",
    label: "نگارش ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112202.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112204",
    value: "112204",
    label: "دین و زندگی ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112204.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112204",
    value: "112204",
    label: "دین و زندگی ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112204.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112206",
    value: "112206",
    label: "عربی، زبان قرآن ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112206.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112206",
    value: "112206",
    label: "عربی، زبان قرآن ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112206.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112210",
    value: "112210",
    label: "شیمی ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112210.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112210",
    value: "112210",
    label: "شیمی ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112210.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112220",
    value: "112220",
    label: "هویت اجتماعی",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112220.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112220",
    value: "112220",
    label: "هویت اجتماعی",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112220.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112228",
    value: "112228",
    label: "تعلیمات ادیان الهی و اخلاق ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112228",
    value: "112228",
    label: "تعلیمات ادیان الهی و اخلاق ۳",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112228",
    value: "112228",
    label: "تعلیمات ادیان الهی و اخلاق ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112228.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112230",
    value: "112230",
    label: "انگلیسی ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112231",
    value: "112231",
    label: "کتاب کار انگلیسی ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112230",
    value: "112230",
    label: "انگلیسی ۳",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112231",
    value: "112231",
    label: "کتاب کار انگلیسی ۳",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112230",
    value: "112230",
    label: "انگلیسی ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112230.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112231",
    value: "112231",
    label: "کتاب کار انگلیسی ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112231.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112240",
    value: "112240",
    label: "مدیریت خانواده و سبک زندگی (دختران)",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112240.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112240",
    value: "112240",
    label: "مدیریت خانواده و سبک زندگی (دختران)",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112240.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112240",
    value: "112240",
    label: "مدیریت خانواده و سبک زندگی (دختران)",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112240.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112245",
    value: "112245",
    label: "مدیریت خانواده و سبک زندگی (پسران)",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112245.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112245",
    value: "112245",
    label: "مدیریت خانواده و سبک زندگی (پسران)",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112245.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112245",
    value: "112245",
    label: "مدیریت خانواده و سبک زندگی (پسران)",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112245.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112268",
    value: "112268",
    label: "سلامت و بهداشت",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112268.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112268",
    value: "112268",
    label: "سلامت و بهداشت",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112268.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112268",
    value: "112268",
    label: "سلامت و بهداشت",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112268.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی تجربی
  {
    id: "112211",
    value: "112211",
    label: "ریاضی ۳ (تجربی)",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112211.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112216",
    value: "112216",
    label: "زیست شناسی ۳",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112216.jpg",
    isAvailable: true,
    lastPage: 125,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112244",
    value: "112244",
    label: "فیزیک ۳ (تجربی)",
    gradeId: 12,
    fieldId: 1,
    coverImage: "@/public/imgs/book-covers/C112244.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی انسانی
  {
    id: "112205",
    value: "112205",
    label: "دین و زندگی ۳ (انسانی)",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112205.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112207",
    value: "112207",
    label: "عربی، زبان قرآن ۳ (انسانی)",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112207.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112212",
    value: "112212",
    label: "ریاضی و آمار ۳",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112212.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112218",
    value: "112218",
    label: "جغرافیا ۳ (کاربردی)",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112218.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112219",
    value: "112219",
    label: "تاریخ ۳ ایران و جهان معاصر",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112219.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112222",
    value: "112222",
    label: "جامعه شناسی ۳",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112222.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112223",
    value: "112223",
    label: "تحلیل فرهنگی",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112223.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112226",
    value: "112226",
    label: "فلسفه ۲",
    gradeId: 12,
    fieldId: 2,
    coverImage: "@/public/imgs/book-covers/C112226.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  // اختصاصی ریاضی
  {
    id: "112209",
    value: "112209",
    label: "فیزیک ۳ (ریاضی)",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112209.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112213",
    value: "112213",
    label: "هندسه ۳",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112213.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112214",
    value: "112214",
    label: "حسابان ۲",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112214.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
  {
    id: "112215",
    value: "112215",
    label: "ریاضیات گسسته",
    gradeId: 12,
    fieldId: 3,
    coverImage: "@/public/imgs/book-covers/C112215.jpg",
    isAvailable: false,
    lastPage: 100,
    publishedYear: 1404,
    hasFinalExam: false,
    isInKonkour: false,
  },
];

export const filterBooksByProp = <K extends keyof Book>(
  books: Book[],
  key: K,
  value: Book[K] | undefined,
): Book[] => {
  if (value === undefined) return books;
  return books.filter((book) => book[key] === value);
};

export const allBooks = BOOKS;
export const getAllBooks = () => allBooks;

export type BooksFilter = {
  gradeId?: GradeId;
  fieldId?: FieldId;
  isAvailable?: boolean;
};

export const isValidBookId = (id: string) => {
  return getAllBooks().some((b) => b.value === id);
};

export const getBooks = (filter: BooksFilter = {}): Book[] => {
  const { gradeId, fieldId, isAvailable } = filter;

  if (!gradeId && !fieldId && isAvailable === undefined) {
    // fekr konam inja bayad data error ro neshoon bedim :)
    return getAllBooks();
  }

  let result = filterBooksByProp(getAllBooks(), "gradeId", gradeId);

  if (gradeId !== undefined && gradeId >= 10) {
    result = filterBooksByProp(result, "fieldId", fieldId);
  }

  if (isAvailable !== undefined) {
    result = result.filter((b) => b.isAvailable === isAvailable);
  }

  return result;
};

export const getBookById = (id: string): Book => filterBooksByProp(getAllBooks(), "id", id)[0];

export const purchasedBooksIds: string[] = ["706", "806", "906"];
// esmo id ketaab haaye moshtarak vaase list option ketaab haa to book selector
// bayad eslaah beshe.
// export const purchasedBooksIds: number[] = getAllBooks().map((book) => book.id);
export const getPurchasedBooksIds = () => purchasedBooksIds;

const purchasedBooks = getPurchasedBooksIds().map((id) => getBookById(id));
export const getPurchasedBooks = () => purchasedBooks;

export type BookOption = {
  value: string;
  label: string;
};
export const getBookSelectOptions = (): BookOption[] => {
  const optionsOfBookSelector = getPurchasedBooks().map((book) => {
    return { value: book.id, label: book.label };
  });
  return optionsOfBookSelector;
};
