import type { Metadata } from "next";
import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import localFont from "next/font/local";
import QueryProvider from "@/components/providers/query-provider";

import "@/public/fonts/material-symbols-rounded.css";

const materialSymbols = localFont({
  src: "../public/fonts/material-symbols-rounded.woff2",
  variable: "--font-material-symbols-rounded",
  display: "swap",
  weight: "100 700", // محدوده وزنی که فونت ساپورت می‌کنه
  style: "normal",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic", "latin"], // خیلی مهم برای پشتیبانی کامل فارسی
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // یا 'variable' اگر variable font بخوای
  display: "swap",
});

export const metadata: Metadata = {
  title: "darsyavar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      // dir="ltr"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.variable,
        vazirmatn.className,
        materialSymbols.variable,
      )}
    >
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
